# apache/vhost.conf
<VirtualHost *:80>
    DocumentRoot "/usr/local/apache2/htdocs"
    TimeOut 240
    ProxyTimeout 240
    
    <Directory "/usr/local/apache2/htdocs">
        Require all granted
        AllowOverride All
        FallbackResource /index.html
    </Directory>

    ProxyPreserveHost On
    ProxyPass /api http://backend:5001/api timeout=240
    ProxyPassReverse /api http://backend:5001/api

</VirtualHost>
